### ISSUE TITLE
end record

### ISSUE THREAD

**Issue by Myster7494** [darksworm/hearthstone-obs-recorder#2]
Can it end recording after the game end a few seconds, otherwise the animation is weird. (My native language is not English, so this is translated by a translator, sorry for the grammatical errors)

**Comment by darksworm** [comment]
Hi @jackychiu0207! Thanks for the suggestion! I hadn't noticed this.

I've made the changes, please check the new version to see whether it is working properly: https://github.com/darksworm/hearthstone-obs-recorder/releases/tag/0.0.0.2

**Comment by Myster7494** [comment]
Thanks.It's can work.
